### ISSUE TITLE
Update to RDF.rb 1.99

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/ld-patch#1]
There's a dependency issue with the upgrade surrounding `ebnf` versions. A quick hack at the upgrade ran into a problem with https://github.com/ruby-rdf/ld-patch/blob/develop/spec/suite_helper.rb#L94 returning an empty repository. 

I can't repeat that error outside of this repository. That's as far as I've taken it so far, but maybe the problem is obvious to you?

**Comment by gkellogg** [comment]
I forgot this one, it's because ~> 0.3 is not compatible with 1.0. I'll fix the gemspec shortly.

**Comment by no-reply** [comment]
Thank you!
